Lic 268/dropdown example
MO-Movia/licit-plugin-contrib-styles pull request #101
Opened 2024-06-28 15:53 UTC by rohanrjohn

2024-06-28 17:34 UTC, Tezra requested changes

2024-06-28 17:34 UTC, Tezra commented on src/CustomStyleCommand.ts
> +        if (undefined === mark.attrs[ATTR_OVERRIDDEN] || (undefined !== mark.attrs[ATTR_OVERRIDDEN] && !mark.attrs[ATTR_OVERRIDDEN])) {
contents of this if should be a function to reduce duplication and clarify what the condition is.

2024-06-28 17:34 UTC, Tezra commented on src/customStyle.ts
> +let _view;
why is the type removed? No any.

2024-06-28 17:34 UTC, Tezra commented on src/customStyle.ts
> +export function addStyleToList(style) {
no any

2024-06-28 17:34 UTC, Tezra commented on src/customStyle.ts
> +export function setView(csview) {
no any

2024-06-28 17:34 UTC, Tezra commented on src/index.ts
> +export function applyStyleForPreviousEmptyParagraph(nextState, tr) {
no any

2024-06-28 17:34 UTC, Tezra commented on src/ui/CustomStyleEditor.tsx
> +let editedStyles = [];
Why is this being changed if it is only being set to `[]` in the constructor?

2024-07-09 11:37 UTC, rodgersgb approved these changes

2024-07-09 11:37 UTC, merged