Delete style
MO-Movia/licit-plugin-contrib-styles pull request #25
Opened 2023-05-12 11:28 UTC by firmusoft

Copy paste of paragraph with style not working

2023-05-17 19:07 UTC, Tezra requested changes
Several things that need to be cleaned up as well as a couple questions.

2023-05-17 19:07 UTC, Tezra commented on src/ui/CustomMenuUI.js
> +import  * as React from 'react';
extra space

2023-05-17 19:07 UTC, Tezra commented on src/CustomStyleCommand.js
> +      case MARK_TEXT_HIGHLIGHT:
MARK_TEXT_HIGHLIGHT is already in this switch. Remove the duplicate case.

2023-05-17 19:07 UTC, Tezra commented on src/CustomStyleCommand.js
>    node: Node,
Why aren't these typescript files?

2023-05-18 14:52 UTC, Tezra approved these changes

2023-05-18 14:52 UTC, Tezra approved these changes

2023-05-23 11:06 UTC, rodgersgb approved these changes

2023-05-23 11:38 UTC, merged