Unit test
MO-Movia/licit-plugin-contrib-styles pull request #32
Opened 2023-09-12 10:41 UTC by Jayakrishnan-MS

Achieved unit test coverage above 80%

2023-09-12 12:37 UTC, Tezra approved these changes

2023-09-12 13:18 UTC, Tezra commented
1. Needs to be synced with develop
2. src/CustomStyleCommand.js: 247; Introduce a new variable or use its initial value before reassigning "newattrs".
3. src/ui/CustomStyleItem.js: 132; No duplicate props allowed.
4. src/CustomStyleCommand.js: 917; Add a "return" statement to this callback. ([javascript:S3796](https://test.modusoperandi.com/sonar/coding_rules?open=javascript%3AS3796&rule_key=javascript%3AS3796))

2023-09-12 13:19 UTC, Tezra requested changes
Needs to be synced with develop
src/CustomStyleCommand.js: 247; Introduce a new variable or use its initial value before reassigning "newattrs".
src/ui/CustomStyleItem.js: 132; No duplicate props allowed.
src/CustomStyleCommand.js: 917; Add a "return" statement to this callback. ([javascript:S3796](https://test.modusoperandi.com/sonar/coding_rules?open=javascript%3AS3796&rule_key=javascript%3AS3796))

2023-09-15 14:42 UTC, Tezra approved these changes

2023-09-19 12:50 UTC, rodgersgb approved these changes

2023-09-19 12:51 UTC, merged