Issue fix/knite 950 style load
MO-Movia/licit-plugin-contrib-styles pull request #60
Opened 2024-04-26 18:21 UTC by rohanrjohn

Fix - In initial load, the styles don't get applied.

2024-04-26 18:44 UTC, Tezra requested changes

2024-04-26 18:44 UTC, Tezra commented on src/ui/CustomMenuUI.test.ts
> +            removeMark: () => {
Could you not just save this object as a variable so that you can make it self-referential and avoid this manual recursion?

2024-04-26 18:44 UTC, Tezra commented on src/index.test.ts
> +  xit('should handle onUpdateAppendTransaction when ENTERKEYCODE === csview.input.lastKeyCode && tr.selection.$from.start() == tr.selection.$from.end() this condition should pass', () => {
why skip?

2024-04-26 18:44 UTC, Tezra commented on src/index.test.ts
> +  xit('should handle onUpdateAppendTransaction when ENTERKEYCODE === csview.input.lastKeyCode && tr.selection.$from.start() == tr.selection.$from.end() this condition should pass', () => {
why skip?

2024-04-26 18:44 UTC, Tezra commented on src/index.test.ts
> +xdescribe('applyStyleForEmptyParagraph', () => {
why skip? especially if you are modifying it.

2024-04-26 18:44 UTC, Tezra commented on src/customStyle.ts
> +    docType = documentType;
If `docType = documentType` regardless, why not just set `hasdocTypechanged = docType !== documentType`?

2024-04-26 18:44 UTC, Tezra commented on src/customStyle.ts
> +export function setStyles(style) {
Why remove typing? param must have a type.

2024-04-26 18:44 UTC, Tezra commented on src/customStyle.ts
> +export function setView(csview) {
param needs type.

2024-04-26 18:44 UTC, Tezra commented on src/customStyle.ts
> +let _view;
needs type

2024-04-26 18:44 UTC, Tezra commented on src/CustomStyleCommand.ts
> +  let content = [];
array type needs type

2024-04-27 08:44 UTC, Jayakrishnan-MS commented on src/index.test.ts
> +  xit('should handle onUpdateAppendTransaction when ENTERKEYCODE === csview.input.lastKeyCode && tr.selection.$from.start() == tr.selection.$from.end() this condition should pass', () => {
Implementation changed

2024-05-02 16:39 UTC, Tezra requested changes
Can you also clean up all the "setState" sonar issues? I suspect those are also contributing to this and similar issues.
Use callback in setState when referencing the previous state.
"setState" should use a callback when referencing the previous state[typescript:S6756](https://test.modusoperandi.com/sonar/coding_rules?open=typescript%3AS6756&rule_key=typescript%3AS6756)

2024-05-02 16:39 UTC, Tezra commented on src/index.test.ts
> +      doc: { content: { size: 0 }, resolve: () => { return { min: () => { return 0; }, max: () => { return 1; } } as unknown as ResolvedPos; }, nodesBetween: () => { return {}; } }, setSelection: ()
use a self reference here for the recursion.

2024-05-02 16:39 UTC, Tezra commented on src/index.test.ts
> +          setSelection: () => { return { doc: { content: { size: 0 }, resolve: () => { return { min: () => { return 0; }, max: () => { return 1; } } as unknown as ResolvedPos; }, nodesBetween: () =>
use a self reference here for the recursion.

2024-05-02 16:39 UTC, Tezra commented on src/index.test.ts
> +              return {
use a self reference here for the recursion.

2024-05-03 07:06 UTC, Jayakrishnan-MS commented
> Can you also clean up all the "setState" sonar issues? I suspect those are also contributing to this and similar issues. Use callback in setState when referencing the previous state. "setState" should use a callback when referencing the previous state[typescript:S6756](https://test.modusoperandi.com/sonar/coding_rules?open=typescript%3AS6756&rule_key=typescript%3AS6756) 
@Tezra ,Changing this will affect the unit test significantly and can decrease the coverage to 70% or less. And it will take sometime to cover that

2024-05-03 12:58 UTC, Tezra approved these changes
Will need a follow up PR to address the sonar issues.

2024-05-09 17:42 UTC, rodgersgb approved these changes

2024-05-09 17:42 UTC, merged